repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: check-xml
      - id: mixed-line-ending
      - id: end-of-file-fixer
